version: '3'

services:
  rr:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
    depends_on:
      - "worker"
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app
      - APP_SECRET_KEY=change_me
      - ENV=DEV
      - TMP_CUSTOM_DIR=/tmp_dir/
      - REDIS_URL=redis://redis:6379
    volumes:
      - app:/rr
      - cache_vol:/tmp_dir/

  redis:
    container_name: redis
    image: "redis:6.0.5-buster"
    depends_on:
      - "worker"
    volumes:
      - "redis:/data"
      
  worker:
    build:
      context: .
      dockerfile: Worker-Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379
      - TMP_CUSTOM_DIR=/tmp_dir/
    volumes:
      - cache_vol:/tmp_dir/

volumes:
  redis: {}
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  app:
