version: '3'

services:
  rr:
    container_name: rottingresearch
    image: rottingresearch/rottingresearch
    depends_on:
      - "worker"
    restart: unless-stopped
    ports:
      - "80:8080"
    deploy:
      constraints: 
        - node.labels.rr == rr  
        - node.labels.rr == rr
    environment:
      - FLASK_APP=app
      - APP_SECRET_KEY=change_me
      - TMP_CUSTOM_DIR=/tmp_dir/
      - REDIS_URL=
    volumes:
      - app:/rr
      - cache_vol:/tmp_dir/
      
  worker:
    container_name: rr-worker
    image: rottingresearch/rottingresearch_worker
    restart: unless-stopped
    deploy:
      constraints: 
        - node.labels.rr == rr  
        - node.labels.rr == rr
    environment:
      - REDIS_URL=
      - TMP_CUSTOM_DIR=/tmp_dir/
    volumes:
      - cache_vol:/tmp_dir/
      
volumes:
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  app:
