version: '3'

services:
  rr:
    container_name: rottingresearch
    image: rottingresearch/rottingresearch
    depends_on:
      - "worker"
    restart: unless-stopped
    ports:
      - "80:8080"
    deploy:
      mode: replicated
        replicas: 1
      constraints: 
        - node.labels.stack == rr  
        - node.labels.stack == rr
    environment:
      - FLASK_APP=app
      - APP_SECRET_KEY=change_me
      - TMP_CUSTOM_DIR=/tmp_dir/
      - REDIS_URL=
    volumes:
      - app:/rr
      - cache_vol:/tmp_dir/
      
  worker:
    container_name: rr-worker
    image: rottingresearch/rottingresearch_worker
    restart: unless-stopped
    deploy:
      mode: replicated
        replicas: 3
      constraints: 
        - node.labels.stack == rr  
        - node.labels.stack == rr
    environment:
      - REDIS_URL=
      - TMP_CUSTOM_DIR=/tmp_dir/
    volumes:
      - cache_vol:/tmp_dir/
  watchtower:
    contrainer_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    depends_on:
      - my_service
      
volumes:
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  app:
