name: rottingresearch
version: 1.0
summary: rottingresearch
description: |
  This script searches a pdf for hyperlinks and tests them for active status or errors returned.
base: core18


parts:
  rottingresearch:
    plugin: python
