name: BrowserStack
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ubuntu-job:
      runs-on: ubuntu-latest
      steps:
      - name: BrowserStack Actions
        uses: browserstack/github-actions@v1.0.1
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: BUILD_INFO
          project-name: REPO_NAME
