# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - RottingResearch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_05462f27a69c425ab7f3766f1642dd12 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e8a1076361724f99b12bdafcac5b141b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_05462f27a69c425ab7f3766f1642dd12 }}/rottingresearch:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'RottingResearch'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1f9c0766f94c4c6999454c086aad4382 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_05462f27a69c425ab7f3766f1642dd12 }}/rottingresearch:${{ github.sha }}'